//! Performance Snapshot - one-click export of all current metrics.
//!
//! Generates a clean text report ready to paste into Reddit, GitHub issues,
//! Discord, or save to a file.

use eframe::egui;
use crate::app::App;
use crate::gui::{theme, widgets};

/// Generate a full system snapshot as formatted text.
fn generate_snapshot(app: &App) -> String {
    let mut s = String::new();
    s.push_str("=== Pane System Snapshot ===\n\n");

    // GPUs
    for (i, gpu) in app.gpus.iter().enumerate() {
        s.push_str(&format!("GPU {}: {}\n", i, gpu.name));
        s.push_str(&format!("  Utilization: {:.0}%\n", gpu.utilization));
        s.push_str(&format!("  VRAM: {} / {} ({:.0}%)\n",
            widgets::format_bytes(gpu.vram_used), widgets::format_bytes(gpu.vram_total), gpu.vram_pct()));
        if let Some(t) = gpu.temp_core {
            s.push_str(&format!("  Temp: {}C", t));
            if let Some(hs) = gpu.temp_hotspot { s.push_str(&format!(" (hotspot {}C)", hs)); }
            s.push('\n');
        }
        if let Some(w) = gpu.power_watts {
            let limit = gpu.power_limit.map(|l| format!(" / {:.0}W limit", l)).unwrap_or_default();
            s.push_str(&format!("  Power: {:.0}W{}\n", w, limit));
        }
        if let Some(c) = gpu.clock_core_mhz { s.push_str(&format!("  Core Clock: {} MHz\n", c)); }
        if let Some(m) = gpu.clock_mem_mhz { s.push_str(&format!("  Mem Clock: {} MHz\n", m)); }
        if let Some(f) = gpu.fan_rpm { s.push_str(&format!("  Fan: {}%\n", f)); }
        if let (Some(tx), Some(rx)) = (gpu.pcie_tx_bytes_sec, gpu.pcie_rx_bytes_sec) {
            s.push_str(&format!("  PCIe: TX {} / RX {}\n", widgets::format_rate(tx), widgets::format_rate(rx)));
        }
        if !gpu.processes.is_empty() {
            s.push_str("  GPU Processes:\n");
            for p in gpu.processes.iter().take(10) {
                s.push_str(&format!("    {} (PID {}) - {}\n", p.name, p.pid, widgets::format_bytes(p.used_gpu_memory)));
            }
        }
        s.push('\n');
    }

    // CPU
    s.push_str(&format!("CPU: {} ({}/{}c)\n", app.cpu.name, app.cpu.physical_cores, app.cpu.logical_cores));
    s.push_str(&format!("  Usage: {:.1}%\n\n", app.cpu.total_usage));

    // Memory
    let mem_pct = if app.memory.total_bytes > 0 {
        (app.memory.used_bytes as f64 / app.memory.total_bytes as f64) * 100.0
    } else { 0.0 };
    s.push_str(&format!("Memory: {} / {} ({:.0}%)\n", widgets::format_bytes(app.memory.used_bytes), widgets::format_bytes(app.memory.total_bytes), mem_pct));
    s.push_str(&format!("Swap: {} / {}\n\n", widgets::format_bytes(app.memory.swap_used), widgets::format_bytes(app.memory.swap_total)));

    // Disks
    s.push_str("Disks:\n");
    for d in &app.disks {
        let pct = if d.total_bytes > 0 { (d.used_bytes as f64 / d.total_bytes as f64) * 100.0 } else { 0.0 };
        s.push_str(&format!("  {} ({}) - {:.0}% used, R:{} W:{}\n",
            d.name, d.mount, pct, widgets::format_rate(d.read_bytes_sec), widgets::format_rate(d.write_bytes_sec)));
    }
    s.push('\n');

    // Top processes
    s.push_str("Top Processes (by CPU):\n");
    let procs = app.sorted_processes();
    for p in procs.iter().take(15) {
        s.push_str(&format!("  {} (PID {}) - CPU: {:.1}%, Mem: {}\n", p.name, p.pid, p.cpu_usage, widgets::format_bytes(p.memory_bytes)));
    }

    s.push_str("\n--- Generated by Pane (github.com/TxsharDev/pane) ---\n");
    s
}

pub fn draw(ui: &mut egui::Ui, app: &App) {
    let p = theme::p();

    egui::ScrollArea::vertical().show(ui, |ui| {
        widgets::section_header(ui, "Performance Snapshot");
        ui.label(egui::RichText::new("Export a clean report of your current system state").size(12.0).color(p.dim));

        ui.add_space(8.0);

        ui.horizontal(|ui| {
            if ui.button(egui::RichText::new("Copy to Clipboard").size(13.0).color(p.accent).strong()).clicked() {
                let snapshot = generate_snapshot(app);
                ui.ctx().copy_text(snapshot);
            }

            if ui.button(egui::RichText::new("Save to File").size(13.0)).clicked() {
                let snapshot = generate_snapshot(app);
                let filename = format!("pane-snapshot-{}.txt", chrono_simple());
                if let Some(desktop) = dirs::desktop_dir() {
                    let path = desktop.join(&filename);
                    let _ = std::fs::write(&path, &snapshot);
                }
            }
        });

        ui.add_space(12.0);

        // Preview
        widgets::section_header(ui, "Preview");
        let snapshot = generate_snapshot(app);

        egui::Frame::NONE
            .fill(p.chart_bg)
            .corner_radius(egui::CornerRadius::same(6))
            .stroke(egui::Stroke::new(1.0, p.border))
            .inner_margin(egui::Margin::same(10))
            .show(ui, |ui| {
                ui.set_min_width(ui.available_width());
                ui.label(egui::RichText::new(&snapshot).size(11.0).monospace().color(p.text));
            });
    });
}

fn chrono_simple() -> String {
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    format!("{}", now)
}
